import { registerSystemHandlers } from './system.js';
import { registerSpaceHandlers } from './spaces.js';
import { registerMemoryHandlers } from './memory.js';
import { registerChatHandlers } from './chats.js';
import { registerGitHandlers } from './git.js';
import { registerConnectionHandlers } from './connections.js';
import { registerFileHandlers } from './files.js';
import { registerProjectHandlers } from './projects.js';
import { registerTriggerHandlers } from './triggers.js';
import { registerGmailHandlers } from './gmail.js';
import { registerDriveHandlers } from './drive.js';
import { registerChromeHandlers } from './chrome.js';
import { registerVaultHandlers } from './vault.js';
import { registerSessionHandlers } from './session.js';
import { registerToolPackageHandlers } from './tool-packages.js';
import { registerInternshipHandlers } from './internship.js';
registerSystemHandlers();
registerSpaceHandlers();
registerMemoryHandlers();
registerChatHandlers();
registerGitHandlers();
registerConnectionHandlers();
registerFileHandlers();
registerProjectHandlers();
registerTriggerHandlers();
registerGmailHandlers();
registerDriveHandlers();
registerChromeHandlers();
registerVaultHandlers();
registerSessionHandlers();
registerToolPackageHandlers();
registerInternshipHandlers();
