import { registerSpaceHandlers } from './spaces.js';
import { registerMemoryHandlers } from './memory.js';
import { registerKnowledgeHandlers } from './knowledge.js';
import { registerChatHandlers } from './chats.js';
import { registerGitHandlers } from './git.js';
import { registerConnectionHandlers } from './connections.js';
import { registerDocumentHandlers } from './documents.js';
import { registerProjectHandlers } from './projects.js';
import { registerTriggerHandlers } from './triggers.js';
import { registerGmailHandlers } from './gmail.js';
import { registerDriveHandlers } from './drive.js';
import { registerChromeHandlers } from './chrome.js';
import { registerVaultHandlers } from './vault.js';
registerSpaceHandlers();
registerMemoryHandlers();
registerKnowledgeHandlers();
registerChatHandlers();
registerGitHandlers();
registerConnectionHandlers();
registerDocumentHandlers();
registerProjectHandlers();
registerTriggerHandlers();
registerGmailHandlers();
registerDriveHandlers();
registerChromeHandlers();
registerVaultHandlers();
